# Generated by Django 3.0.6 on 2020-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformapp', '0003_auto_20200517_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='last_edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='last_edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tab',
            name='last_edit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
